@startuml
title ILP Universal transaction mode Summary.\n REF: https://github.com/interledger/rfcs/blob/master/0003-interledger-protocol/0003-interledger-protocol.md
participant "buyer\n(payment sender)" as app
participant "ILP enabled\n settlement ledger1" as ledger1
participant "ILP\nconnector1" as connector

note over app, connector
   The ILP packet containing destination_address, amount and cryptocondition is
negotiated in the pre-payment phase between the buyer (or sending app/wallet/...) 
and the payment beneficiary (seller/...)\n. (Amount unit: base unit in destination
 ledger)
 end note

app -> ledger1: ILP payment packet
ledger1 -> ledger1: extract condition from ILP payment packet
' TODO:(0) What's the initial ammount?
ledger1 -> ledger1: new local transaction\n sender ->(ammount) -> hold \n(attach crypto-condition)
ledger1 -> connector: notifies ILP-prepare
connector -> connector: extracts ILP packet
@enduml

